name: "Node.js feature CI"

on:
  repository_dispatch:
    types:
      - webhook2
  schedule:
    - cron: '5 12 * * 0'

jobs:
  my-job:
    runs-on: ubuntu-latest
    steps:
      - name: my-step
        run: echo "Hello World!"
