name: "Node.js CI"

on:
  repository_dispatch:
    types:
      - webhook
  push:
    branches:
      - master
jobs:
  my-job:
    runs-on: ubuntu-latest
    steps:
      - name: my-step
        run: echo "Hello World!"
